// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: hal.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HalService_GetSystemStatus_FullMethodName = "/hal.HalService/GetSystemStatus"
	HalService_SendCommand_FullMethodName     = "/hal.HalService/SendCommand"
	HalService_GetValue_FullMethodName        = "/hal.HalService/GetValue"
	HalService_QueryPins_FullMethodName       = "/hal.HalService/QueryPins"
	HalService_QuerySignals_FullMethodName    = "/hal.HalService/QuerySignals"
	HalService_QueryParams_FullMethodName     = "/hal.HalService/QueryParams"
	HalService_QueryComponents_FullMethodName = "/hal.HalService/QueryComponents"
	HalService_StreamStatus_FullMethodName    = "/hal.HalService/StreamStatus"
	HalService_WatchValues_FullMethodName     = "/hal.HalService/WatchValues"
)

// HalServiceClient is the client API for HalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HalServiceClient interface {
	// Get complete HAL system status
	GetSystemStatus(ctx context.Context, in *GetSystemStatusRequest, opts ...grpc.CallOption) (*HalSystemStatus, error)
	// Send a command
	SendCommand(ctx context.Context, in *HalCommand, opts ...grpc.CallOption) (*HalCommandResponse, error)
	// Get a single value
	GetValue(ctx context.Context, in *GetValueCommand, opts ...grpc.CallOption) (*GetValueResponse, error)
	// Query pins
	QueryPins(ctx context.Context, in *QueryPinsCommand, opts ...grpc.CallOption) (*QueryPinsResponse, error)
	// Query signals
	QuerySignals(ctx context.Context, in *QuerySignalsCommand, opts ...grpc.CallOption) (*QuerySignalsResponse, error)
	// Query parameters
	QueryParams(ctx context.Context, in *QueryParamsCommand, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Query components
	QueryComponents(ctx context.Context, in *QueryComponentsCommand, opts ...grpc.CallOption) (*QueryComponentsResponse, error)
	// Stream system status updates
	StreamStatus(ctx context.Context, in *HalStreamStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HalSystemStatus], error)
	// Watch for value changes
	WatchValues(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ValueChangeBatch], error)
}

type halServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHalServiceClient(cc grpc.ClientConnInterface) HalServiceClient {
	return &halServiceClient{cc}
}

func (c *halServiceClient) GetSystemStatus(ctx context.Context, in *GetSystemStatusRequest, opts ...grpc.CallOption) (*HalSystemStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HalSystemStatus)
	err := c.cc.Invoke(ctx, HalService_GetSystemStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *halServiceClient) SendCommand(ctx context.Context, in *HalCommand, opts ...grpc.CallOption) (*HalCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HalCommandResponse)
	err := c.cc.Invoke(ctx, HalService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *halServiceClient) GetValue(ctx context.Context, in *GetValueCommand, opts ...grpc.CallOption) (*GetValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, HalService_GetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *halServiceClient) QueryPins(ctx context.Context, in *QueryPinsCommand, opts ...grpc.CallOption) (*QueryPinsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPinsResponse)
	err := c.cc.Invoke(ctx, HalService_QueryPins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *halServiceClient) QuerySignals(ctx context.Context, in *QuerySignalsCommand, opts ...grpc.CallOption) (*QuerySignalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySignalsResponse)
	err := c.cc.Invoke(ctx, HalService_QuerySignals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *halServiceClient) QueryParams(ctx context.Context, in *QueryParamsCommand, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, HalService_QueryParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *halServiceClient) QueryComponents(ctx context.Context, in *QueryComponentsCommand, opts ...grpc.CallOption) (*QueryComponentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryComponentsResponse)
	err := c.cc.Invoke(ctx, HalService_QueryComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *halServiceClient) StreamStatus(ctx context.Context, in *HalStreamStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HalSystemStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HalService_ServiceDesc.Streams[0], HalService_StreamStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HalStreamStatusRequest, HalSystemStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HalService_StreamStatusClient = grpc.ServerStreamingClient[HalSystemStatus]

func (c *halServiceClient) WatchValues(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ValueChangeBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HalService_ServiceDesc.Streams[1], HalService_WatchValues_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, ValueChangeBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HalService_WatchValuesClient = grpc.ServerStreamingClient[ValueChangeBatch]

// HalServiceServer is the server API for HalService service.
// All implementations must embed UnimplementedHalServiceServer
// for forward compatibility.
type HalServiceServer interface {
	// Get complete HAL system status
	GetSystemStatus(context.Context, *GetSystemStatusRequest) (*HalSystemStatus, error)
	// Send a command
	SendCommand(context.Context, *HalCommand) (*HalCommandResponse, error)
	// Get a single value
	GetValue(context.Context, *GetValueCommand) (*GetValueResponse, error)
	// Query pins
	QueryPins(context.Context, *QueryPinsCommand) (*QueryPinsResponse, error)
	// Query signals
	QuerySignals(context.Context, *QuerySignalsCommand) (*QuerySignalsResponse, error)
	// Query parameters
	QueryParams(context.Context, *QueryParamsCommand) (*QueryParamsResponse, error)
	// Query components
	QueryComponents(context.Context, *QueryComponentsCommand) (*QueryComponentsResponse, error)
	// Stream system status updates
	StreamStatus(*HalStreamStatusRequest, grpc.ServerStreamingServer[HalSystemStatus]) error
	// Watch for value changes
	WatchValues(*WatchRequest, grpc.ServerStreamingServer[ValueChangeBatch]) error
	mustEmbedUnimplementedHalServiceServer()
}

// UnimplementedHalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHalServiceServer struct{}

func (UnimplementedHalServiceServer) GetSystemStatus(context.Context, *GetSystemStatusRequest) (*HalSystemStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemStatus not implemented")
}
func (UnimplementedHalServiceServer) SendCommand(context.Context, *HalCommand) (*HalCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedHalServiceServer) GetValue(context.Context, *GetValueCommand) (*GetValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedHalServiceServer) QueryPins(context.Context, *QueryPinsCommand) (*QueryPinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPins not implemented")
}
func (UnimplementedHalServiceServer) QuerySignals(context.Context, *QuerySignalsCommand) (*QuerySignalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuerySignals not implemented")
}
func (UnimplementedHalServiceServer) QueryParams(context.Context, *QueryParamsCommand) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryParams not implemented")
}
func (UnimplementedHalServiceServer) QueryComponents(context.Context, *QueryComponentsCommand) (*QueryComponentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryComponents not implemented")
}
func (UnimplementedHalServiceServer) StreamStatus(*HalStreamStatusRequest, grpc.ServerStreamingServer[HalSystemStatus]) error {
	return status.Errorf(codes.Unimplemented, "method StreamStatus not implemented")
}
func (UnimplementedHalServiceServer) WatchValues(*WatchRequest, grpc.ServerStreamingServer[ValueChangeBatch]) error {
	return status.Errorf(codes.Unimplemented, "method WatchValues not implemented")
}
func (UnimplementedHalServiceServer) mustEmbedUnimplementedHalServiceServer() {}
func (UnimplementedHalServiceServer) testEmbeddedByValue()                    {}

// UnsafeHalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HalServiceServer will
// result in compilation errors.
type UnsafeHalServiceServer interface {
	mustEmbedUnimplementedHalServiceServer()
}

func RegisterHalServiceServer(s grpc.ServiceRegistrar, srv HalServiceServer) {
	// If the following call pancis, it indicates UnimplementedHalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HalService_ServiceDesc, srv)
}

func _HalService_GetSystemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HalServiceServer).GetSystemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HalService_GetSystemStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HalServiceServer).GetSystemStatus(ctx, req.(*GetSystemStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HalService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HalCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HalServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HalService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HalServiceServer).SendCommand(ctx, req.(*HalCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _HalService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HalServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HalService_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HalServiceServer).GetValue(ctx, req.(*GetValueCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _HalService_QueryPins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPinsCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HalServiceServer).QueryPins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HalService_QueryPins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HalServiceServer).QueryPins(ctx, req.(*QueryPinsCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _HalService_QuerySignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySignalsCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HalServiceServer).QuerySignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HalService_QuerySignals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HalServiceServer).QuerySignals(ctx, req.(*QuerySignalsCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _HalService_QueryParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HalServiceServer).QueryParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HalService_QueryParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HalServiceServer).QueryParams(ctx, req.(*QueryParamsCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _HalService_QueryComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryComponentsCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HalServiceServer).QueryComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HalService_QueryComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HalServiceServer).QueryComponents(ctx, req.(*QueryComponentsCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _HalService_StreamStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HalStreamStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HalServiceServer).StreamStatus(m, &grpc.GenericServerStream[HalStreamStatusRequest, HalSystemStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HalService_StreamStatusServer = grpc.ServerStreamingServer[HalSystemStatus]

func _HalService_WatchValues_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HalServiceServer).WatchValues(m, &grpc.GenericServerStream[WatchRequest, ValueChangeBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HalService_WatchValuesServer = grpc.ServerStreamingServer[ValueChangeBatch]

// HalService_ServiceDesc is the grpc.ServiceDesc for HalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hal.HalService",
	HandlerType: (*HalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemStatus",
			Handler:    _HalService_GetSystemStatus_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _HalService_SendCommand_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _HalService_GetValue_Handler,
		},
		{
			MethodName: "QueryPins",
			Handler:    _HalService_QueryPins_Handler,
		},
		{
			MethodName: "QuerySignals",
			Handler:    _HalService_QuerySignals_Handler,
		},
		{
			MethodName: "QueryParams",
			Handler:    _HalService_QueryParams_Handler,
		},
		{
			MethodName: "QueryComponents",
			Handler:    _HalService_QueryComponents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStatus",
			Handler:       _HalService_StreamStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchValues",
			Handler:       _HalService_WatchValues_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hal.proto",
}
