// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: linuxcnc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LinuxCNCService_GetStatus_FullMethodName    = "/linuxcnc.LinuxCNCService/GetStatus"
	LinuxCNCService_SendCommand_FullMethodName  = "/linuxcnc.LinuxCNCService/SendCommand"
	LinuxCNCService_WaitComplete_FullMethodName = "/linuxcnc.LinuxCNCService/WaitComplete"
	LinuxCNCService_StreamStatus_FullMethodName = "/linuxcnc.LinuxCNCService/StreamStatus"
	LinuxCNCService_StreamErrors_FullMethodName = "/linuxcnc.LinuxCNCService/StreamErrors"
)

// LinuxCNCServiceClient is the client API for LinuxCNCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinuxCNCServiceClient interface {
	// Get current status (poll equivalent)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*LinuxCNCStatus, error)
	// Send a command
	SendCommand(ctx context.Context, in *LinuxCNCCommand, opts ...grpc.CallOption) (*CommandResponse, error)
	// Wait for command completion
	WaitComplete(ctx context.Context, in *WaitCompleteRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// Stream status updates
	StreamStatus(ctx context.Context, in *StreamStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LinuxCNCStatus], error)
	// Stream errors
	StreamErrors(ctx context.Context, in *StreamErrorsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ErrorMessage], error)
}

type linuxCNCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLinuxCNCServiceClient(cc grpc.ClientConnInterface) LinuxCNCServiceClient {
	return &linuxCNCServiceClient{cc}
}

func (c *linuxCNCServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*LinuxCNCStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinuxCNCStatus)
	err := c.cc.Invoke(ctx, LinuxCNCService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linuxCNCServiceClient) SendCommand(ctx context.Context, in *LinuxCNCCommand, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, LinuxCNCService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linuxCNCServiceClient) WaitComplete(ctx context.Context, in *WaitCompleteRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, LinuxCNCService_WaitComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linuxCNCServiceClient) StreamStatus(ctx context.Context, in *StreamStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LinuxCNCStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LinuxCNCService_ServiceDesc.Streams[0], LinuxCNCService_StreamStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamStatusRequest, LinuxCNCStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LinuxCNCService_StreamStatusClient = grpc.ServerStreamingClient[LinuxCNCStatus]

func (c *linuxCNCServiceClient) StreamErrors(ctx context.Context, in *StreamErrorsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ErrorMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LinuxCNCService_ServiceDesc.Streams[1], LinuxCNCService_StreamErrors_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamErrorsRequest, ErrorMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LinuxCNCService_StreamErrorsClient = grpc.ServerStreamingClient[ErrorMessage]

// LinuxCNCServiceServer is the server API for LinuxCNCService service.
// All implementations must embed UnimplementedLinuxCNCServiceServer
// for forward compatibility.
type LinuxCNCServiceServer interface {
	// Get current status (poll equivalent)
	GetStatus(context.Context, *GetStatusRequest) (*LinuxCNCStatus, error)
	// Send a command
	SendCommand(context.Context, *LinuxCNCCommand) (*CommandResponse, error)
	// Wait for command completion
	WaitComplete(context.Context, *WaitCompleteRequest) (*CommandResponse, error)
	// Stream status updates
	StreamStatus(*StreamStatusRequest, grpc.ServerStreamingServer[LinuxCNCStatus]) error
	// Stream errors
	StreamErrors(*StreamErrorsRequest, grpc.ServerStreamingServer[ErrorMessage]) error
	mustEmbedUnimplementedLinuxCNCServiceServer()
}

// UnimplementedLinuxCNCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLinuxCNCServiceServer struct{}

func (UnimplementedLinuxCNCServiceServer) GetStatus(context.Context, *GetStatusRequest) (*LinuxCNCStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedLinuxCNCServiceServer) SendCommand(context.Context, *LinuxCNCCommand) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedLinuxCNCServiceServer) WaitComplete(context.Context, *WaitCompleteRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitComplete not implemented")
}
func (UnimplementedLinuxCNCServiceServer) StreamStatus(*StreamStatusRequest, grpc.ServerStreamingServer[LinuxCNCStatus]) error {
	return status.Errorf(codes.Unimplemented, "method StreamStatus not implemented")
}
func (UnimplementedLinuxCNCServiceServer) StreamErrors(*StreamErrorsRequest, grpc.ServerStreamingServer[ErrorMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamErrors not implemented")
}
func (UnimplementedLinuxCNCServiceServer) mustEmbedUnimplementedLinuxCNCServiceServer() {}
func (UnimplementedLinuxCNCServiceServer) testEmbeddedByValue()                         {}

// UnsafeLinuxCNCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinuxCNCServiceServer will
// result in compilation errors.
type UnsafeLinuxCNCServiceServer interface {
	mustEmbedUnimplementedLinuxCNCServiceServer()
}

func RegisterLinuxCNCServiceServer(s grpc.ServiceRegistrar, srv LinuxCNCServiceServer) {
	// If the following call pancis, it indicates UnimplementedLinuxCNCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LinuxCNCService_ServiceDesc, srv)
}

func _LinuxCNCService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinuxCNCServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinuxCNCService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinuxCNCServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinuxCNCService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinuxCNCCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinuxCNCServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinuxCNCService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinuxCNCServiceServer).SendCommand(ctx, req.(*LinuxCNCCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinuxCNCService_WaitComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinuxCNCServiceServer).WaitComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinuxCNCService_WaitComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinuxCNCServiceServer).WaitComplete(ctx, req.(*WaitCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinuxCNCService_StreamStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LinuxCNCServiceServer).StreamStatus(m, &grpc.GenericServerStream[StreamStatusRequest, LinuxCNCStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LinuxCNCService_StreamStatusServer = grpc.ServerStreamingServer[LinuxCNCStatus]

func _LinuxCNCService_StreamErrors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamErrorsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LinuxCNCServiceServer).StreamErrors(m, &grpc.GenericServerStream[StreamErrorsRequest, ErrorMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LinuxCNCService_StreamErrorsServer = grpc.ServerStreamingServer[ErrorMessage]

// LinuxCNCService_ServiceDesc is the grpc.ServiceDesc for LinuxCNCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinuxCNCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linuxcnc.LinuxCNCService",
	HandlerType: (*LinuxCNCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _LinuxCNCService_GetStatus_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _LinuxCNCService_SendCommand_Handler,
		},
		{
			MethodName: "WaitComplete",
			Handler:    _LinuxCNCService_WaitComplete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStatus",
			Handler:       _LinuxCNCService_StreamStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamErrors",
			Handler:       _LinuxCNCService_StreamErrors_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "linuxcnc.proto",
}
