# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hal_pb2 as hal__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HalServiceStub(object):
    """============================================================================
    SERVICE DEFINITIONS (for gRPC if needed)
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemStatus = channel.unary_unary(
                '/hal.HalService/GetSystemStatus',
                request_serializer=hal__pb2.GetSystemStatusRequest.SerializeToString,
                response_deserializer=hal__pb2.HalSystemStatus.FromString,
                _registered_method=True)
        self.SendCommand = channel.unary_unary(
                '/hal.HalService/SendCommand',
                request_serializer=hal__pb2.HalCommand.SerializeToString,
                response_deserializer=hal__pb2.HalCommandResponse.FromString,
                _registered_method=True)
        self.GetValue = channel.unary_unary(
                '/hal.HalService/GetValue',
                request_serializer=hal__pb2.GetValueCommand.SerializeToString,
                response_deserializer=hal__pb2.GetValueResponse.FromString,
                _registered_method=True)
        self.QueryPins = channel.unary_unary(
                '/hal.HalService/QueryPins',
                request_serializer=hal__pb2.QueryPinsCommand.SerializeToString,
                response_deserializer=hal__pb2.QueryPinsResponse.FromString,
                _registered_method=True)
        self.QuerySignals = channel.unary_unary(
                '/hal.HalService/QuerySignals',
                request_serializer=hal__pb2.QuerySignalsCommand.SerializeToString,
                response_deserializer=hal__pb2.QuerySignalsResponse.FromString,
                _registered_method=True)
        self.QueryParams = channel.unary_unary(
                '/hal.HalService/QueryParams',
                request_serializer=hal__pb2.QueryParamsCommand.SerializeToString,
                response_deserializer=hal__pb2.QueryParamsResponse.FromString,
                _registered_method=True)
        self.QueryComponents = channel.unary_unary(
                '/hal.HalService/QueryComponents',
                request_serializer=hal__pb2.QueryComponentsCommand.SerializeToString,
                response_deserializer=hal__pb2.QueryComponentsResponse.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/hal.HalService/StreamStatus',
                request_serializer=hal__pb2.HalStreamStatusRequest.SerializeToString,
                response_deserializer=hal__pb2.HalSystemStatus.FromString,
                _registered_method=True)
        self.WatchValues = channel.unary_stream(
                '/hal.HalService/WatchValues',
                request_serializer=hal__pb2.WatchRequest.SerializeToString,
                response_deserializer=hal__pb2.ValueChangeBatch.FromString,
                _registered_method=True)


class HalServiceServicer(object):
    """============================================================================
    SERVICE DEFINITIONS (for gRPC if needed)
    ============================================================================

    """

    def GetSystemStatus(self, request, context):
        """Get complete HAL system status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommand(self, request, context):
        """Send a command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValue(self, request, context):
        """Get a single value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPins(self, request, context):
        """Query pins
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySignals(self, request, context):
        """Query signals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryParams(self, request, context):
        """Query parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryComponents(self, request, context):
        """Query components
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Stream system status updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchValues(self, request, context):
        """Watch for value changes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=hal__pb2.GetSystemStatusRequest.FromString,
                    response_serializer=hal__pb2.HalSystemStatus.SerializeToString,
            ),
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=hal__pb2.HalCommand.FromString,
                    response_serializer=hal__pb2.HalCommandResponse.SerializeToString,
            ),
            'GetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValue,
                    request_deserializer=hal__pb2.GetValueCommand.FromString,
                    response_serializer=hal__pb2.GetValueResponse.SerializeToString,
            ),
            'QueryPins': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPins,
                    request_deserializer=hal__pb2.QueryPinsCommand.FromString,
                    response_serializer=hal__pb2.QueryPinsResponse.SerializeToString,
            ),
            'QuerySignals': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySignals,
                    request_deserializer=hal__pb2.QuerySignalsCommand.FromString,
                    response_serializer=hal__pb2.QuerySignalsResponse.SerializeToString,
            ),
            'QueryParams': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryParams,
                    request_deserializer=hal__pb2.QueryParamsCommand.FromString,
                    response_serializer=hal__pb2.QueryParamsResponse.SerializeToString,
            ),
            'QueryComponents': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryComponents,
                    request_deserializer=hal__pb2.QueryComponentsCommand.FromString,
                    response_serializer=hal__pb2.QueryComponentsResponse.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=hal__pb2.HalStreamStatusRequest.FromString,
                    response_serializer=hal__pb2.HalSystemStatus.SerializeToString,
            ),
            'WatchValues': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchValues,
                    request_deserializer=hal__pb2.WatchRequest.FromString,
                    response_serializer=hal__pb2.ValueChangeBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hal.HalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hal.HalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HalService(object):
    """============================================================================
    SERVICE DEFINITIONS (for gRPC if needed)
    ============================================================================

    """

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.HalService/GetSystemStatus',
            hal__pb2.GetSystemStatusRequest.SerializeToString,
            hal__pb2.HalSystemStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.HalService/SendCommand',
            hal__pb2.HalCommand.SerializeToString,
            hal__pb2.HalCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.HalService/GetValue',
            hal__pb2.GetValueCommand.SerializeToString,
            hal__pb2.GetValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.HalService/QueryPins',
            hal__pb2.QueryPinsCommand.SerializeToString,
            hal__pb2.QueryPinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.HalService/QuerySignals',
            hal__pb2.QuerySignalsCommand.SerializeToString,
            hal__pb2.QuerySignalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.HalService/QueryParams',
            hal__pb2.QueryParamsCommand.SerializeToString,
            hal__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryComponents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.HalService/QueryComponents',
            hal__pb2.QueryComponentsCommand.SerializeToString,
            hal__pb2.QueryComponentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hal.HalService/StreamStatus',
            hal__pb2.HalStreamStatusRequest.SerializeToString,
            hal__pb2.HalSystemStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hal.HalService/WatchValues',
            hal__pb2.WatchRequest.SerializeToString,
            hal__pb2.ValueChangeBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
