# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import linuxcnc_pb2 as linuxcnc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in linuxcnc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LinuxCNCServiceStub(object):
    """============================================================================
    SERVICE DEFINITIONS (for gRPC if needed)
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/linuxcnc.LinuxCNCService/GetStatus',
                request_serializer=linuxcnc__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=linuxcnc__pb2.LinuxCNCStatus.FromString,
                _registered_method=True)
        self.SendCommand = channel.unary_unary(
                '/linuxcnc.LinuxCNCService/SendCommand',
                request_serializer=linuxcnc__pb2.LinuxCNCCommand.SerializeToString,
                response_deserializer=linuxcnc__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.WaitComplete = channel.unary_unary(
                '/linuxcnc.LinuxCNCService/WaitComplete',
                request_serializer=linuxcnc__pb2.WaitCompleteRequest.SerializeToString,
                response_deserializer=linuxcnc__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/linuxcnc.LinuxCNCService/StreamStatus',
                request_serializer=linuxcnc__pb2.StreamStatusRequest.SerializeToString,
                response_deserializer=linuxcnc__pb2.LinuxCNCStatus.FromString,
                _registered_method=True)
        self.StreamErrors = channel.unary_stream(
                '/linuxcnc.LinuxCNCService/StreamErrors',
                request_serializer=linuxcnc__pb2.StreamErrorsRequest.SerializeToString,
                response_deserializer=linuxcnc__pb2.ErrorMessage.FromString,
                _registered_method=True)
        self.UploadFile = channel.unary_unary(
                '/linuxcnc.LinuxCNCService/UploadFile',
                request_serializer=linuxcnc__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=linuxcnc__pb2.UploadFileResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/linuxcnc.LinuxCNCService/ListFiles',
                request_serializer=linuxcnc__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=linuxcnc__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/linuxcnc.LinuxCNCService/DeleteFile',
                request_serializer=linuxcnc__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=linuxcnc__pb2.DeleteFileResponse.FromString,
                _registered_method=True)


class LinuxCNCServiceServicer(object):
    """============================================================================
    SERVICE DEFINITIONS (for gRPC if needed)
    ============================================================================

    """

    def GetStatus(self, request, context):
        """Get current status (poll equivalent)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommand(self, request, context):
        """Send a command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitComplete(self, request, context):
        """Wait for command completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Stream status updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamErrors(self, request, context):
        """Stream errors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request, context):
        """Upload a G-code file to the nc_files directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """List files in the nc_files directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Delete a file from the nc_files directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LinuxCNCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=linuxcnc__pb2.GetStatusRequest.FromString,
                    response_serializer=linuxcnc__pb2.LinuxCNCStatus.SerializeToString,
            ),
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=linuxcnc__pb2.LinuxCNCCommand.FromString,
                    response_serializer=linuxcnc__pb2.CommandResponse.SerializeToString,
            ),
            'WaitComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitComplete,
                    request_deserializer=linuxcnc__pb2.WaitCompleteRequest.FromString,
                    response_serializer=linuxcnc__pb2.CommandResponse.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=linuxcnc__pb2.StreamStatusRequest.FromString,
                    response_serializer=linuxcnc__pb2.LinuxCNCStatus.SerializeToString,
            ),
            'StreamErrors': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamErrors,
                    request_deserializer=linuxcnc__pb2.StreamErrorsRequest.FromString,
                    response_serializer=linuxcnc__pb2.ErrorMessage.SerializeToString,
            ),
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=linuxcnc__pb2.UploadFileRequest.FromString,
                    response_serializer=linuxcnc__pb2.UploadFileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=linuxcnc__pb2.ListFilesRequest.FromString,
                    response_serializer=linuxcnc__pb2.ListFilesResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=linuxcnc__pb2.DeleteFileRequest.FromString,
                    response_serializer=linuxcnc__pb2.DeleteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'linuxcnc.LinuxCNCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('linuxcnc.LinuxCNCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LinuxCNCService(object):
    """============================================================================
    SERVICE DEFINITIONS (for gRPC if needed)
    ============================================================================

    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc.LinuxCNCService/GetStatus',
            linuxcnc__pb2.GetStatusRequest.SerializeToString,
            linuxcnc__pb2.LinuxCNCStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc.LinuxCNCService/SendCommand',
            linuxcnc__pb2.LinuxCNCCommand.SerializeToString,
            linuxcnc__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc.LinuxCNCService/WaitComplete',
            linuxcnc__pb2.WaitCompleteRequest.SerializeToString,
            linuxcnc__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/linuxcnc.LinuxCNCService/StreamStatus',
            linuxcnc__pb2.StreamStatusRequest.SerializeToString,
            linuxcnc__pb2.LinuxCNCStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/linuxcnc.LinuxCNCService/StreamErrors',
            linuxcnc__pb2.StreamErrorsRequest.SerializeToString,
            linuxcnc__pb2.ErrorMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc.LinuxCNCService/UploadFile',
            linuxcnc__pb2.UploadFileRequest.SerializeToString,
            linuxcnc__pb2.UploadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc.LinuxCNCService/ListFiles',
            linuxcnc__pb2.ListFilesRequest.SerializeToString,
            linuxcnc__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxcnc.LinuxCNCService/DeleteFile',
            linuxcnc__pb2.DeleteFileRequest.SerializeToString,
            linuxcnc__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
